### ISSUE TITLE
Maybe a bug 

### ISSUE THREAD

**Issue by mario6714** [Jeffchen54/KMPDownloader#11]
From this link:

https://kemono.party/patreon/user/11039562?o=0

and this:

KMPDownloader.py -v -u -o -m -t 2 -d D:\KMPDownloader\

nothing happen (see screenshot), just frozen in "Finished scanning"

![imagen](https://user-images.githubusercontent.com/32179719/220446415-b9ca587c-bc2a-44b7-a70a-e1aec6567548.png)

Thanks

**Comment by Jeffchen54** [comment]
Thanks for letting me know. This problem is due to Kemono party updating their links to point to a complete url instead of the old incomplete url. I am working on a fix which will be released by the end of today. I will push a release when I am done implementing this fix.

**Comment by mario6714** [comment]
> Thanks for letting me know. This problem is due to Kemono party updating their links to point to a complete url instead of the old incomplete url. I am working on a fix which will be released by the end of today. I will push a release when I am done implementing this fix.

Thanks

**Comment by Jeffchen54** [comment]
Hotfix has been released in https://github.com/Jeffchen54/KMP-Kemono-Downloader/releases/tag/v0.6.1.2-pre
