### ISSUE TITLE
A Request

### ISSUE THREAD

**Issue by mario6714** [Jeffchen54/KMPDownloader#13]
Hi, one question:

If a download a artist and have psd files and zip files

After convert the psd files to png and uncompress the zip files and delete the zip files if a look again we download again the psd files and psd files right?

I see a command called UPDATE i think, can you create a list somewhere to avoid download again the psd files and zip files and other extensions?

Thanks

**Comment by Jeffchen54** [comment]
The script doesn't convert psd to png automatically. As a result, PSD files are not skipped (if you didn't change its name) but uncompressed zip files are downloaded again. I currently have the feature to skip all duplicate files on the roadmap for 0.7.x. After I get everything in 0.6.x finished.

The UPDATE switch is a bit complex. It will solve the problem you have with duplicate files if you use the --track  or -b switch when downloading items. Afterwards, you can call --UPDATE to update all of the tracked entries without redownloading new files. You can view more details [here](https://github.com/Jeffchen54/KMP-Kemono-Downloader/wiki/Usage#updater)

**Comment by mario6714** [comment]
ah, sorry, is not your program for convert psd to png, i use "XnConvert" for that

**Comment by mario6714** [comment]
i don't know if you can make a record for example the url from the post or the url from the files for avoid to download again in cases for example i download a psd file but i use this tool "XnConvert" for convert from psd into png, but if a check for new updates the program will download again the psd file right? 

"UPDATE" can do that?

**Comment by mario6714** [comment]
I use this commands "KMPDownloader.py -v -u -o -m -b -t 2 -d D:\KMPDownloader\"

-b is for track right?

but i open the KMD.db (KMP - copia.db) file and is nothing there:

![imagen](https://user-images.githubusercontent.com/32179719/225202756-1b8697a9-1b28-466e-924b-a841db8554f5.png)

**Comment by Jeffchen54** [comment]
Did you download something afterwards? You'll need the full artist url link, not a single work or using ?50 or some other number in your URL. If you did, close and reopen it.

Also, make sure that you are using 0.6.1.3

**Comment by mario6714** [comment]
I use this:

KMPDownloader.py -v -u -o -m -b -t 2 -d D:\KMPDownloader

and after that i use again:

KMPDownloader.py -v -u -o -m -b -t 2 -d D:\KMPDownloader

for the same artist after convert clip into jpg but is dowload again the clip files

URL i use: https://kemono.party/patreon/user/70601937

**Comment by mario6714** [comment]
about the version, how i can check in your program? i think i have the last one

**Comment by Jeffchen54** [comment]
If you open up KMPDownloader.py in the text file or code editor, you will see a comment below the imports which states what version you are on.

After initially calling 
python KMPDownloader.py -v -u -o -m -b -t 2 -d D:\KMPDownloader

You will need to call
python KMPDownloader.py -v -u -o -m -t 2 --UPDATE  

To update the entries 

If you call "python KMPDownloader.py -v -u -o -m -b -t 2 -d D:\KMPDownloader" like you did again, it will redownload everything and change the destination of the artist somewhere else indicated by the -d switch.

**Comment by mario6714** [comment]
I just download the last from releases, ok, so one time (per artist):

KMPDownloader.py -v -u -o -m -b -t 2 -d D:\KMPDownloader

and the next one just:

KMPDownloader.py -v -u -o -m -t 2 --UPDATE

One question , if i have 20 artists i need repeat the process right, but after that i only need this?

KMPDownloader.py -v -u -o -m -t 2 --UPDATE

Using this i can avoid download the zip, psd and clip files again?

**Comment by Jeffchen54** [comment]
Yes, you will have to call 'KMPDownloader.py -v -u -o -m -b -t 2 -d D:\KMPDownloader' initially on any artist you want to track. there isn't a limit on the number of tracked artist you can update with the UPDATE switch. I have successfully updated several hundred during testing. The only issue with scalability is if you computer has enough RAM. 

You can avoid downloading any file you downloaded previously using --UPDATE.

**Comment by mario6714** [comment]
Cool, another question,

I need wait the process end for see a more recent update date?

![imagen](https://user-images.githubusercontent.com/32179719/225205319-fd3d9c48-b0a9-4b85-9c09-dfc1a7f05146.png)

**Comment by Jeffchen54** [comment]
Yeah, KMP.db updates only after KMPDownloader has finished running. You will not see any changes while the program is running already. However, DB Browser will not see the changes made to KMP.db when KMPDownloader is finished so you will have to close and reopen KMP.db to view the changes. 

Also, UPDATE will set the latest URLs automatically so you will not redownload any of the new URLs you download through --UPDATE.

**Comment by mario6714** [comment]
Ok, thanks, is working
