### ISSUE TITLE
 ImportError: cannot import name DEFAULT_CIPHERS (Fixed)

### ISSUE THREAD

**Issue by EIKO4O4** [Jeffchen54/KMPDownloader#16]
An error occurred when I run the program under python3.11 (and all the libs are the latest) :

**Fixing method : install a version < 2. `pip install 'urllib3<2'`**

> Traceback (most recent call last):
File "D:\Programs\KMP-Kemono-Downloader-0.6.1.2-pre\KMP-Kemono-Downloader-0.6.1.3-pre\KMPDownloader.py", line 12, in <module>
    import cfscrape
  File "C:\Program Files\Python311\Lib\site-packages\cfscrape\__init__.py", line 19, in <module>
    from urllib3.util.ssl_ import create_urllib3_context, DEFAULT_CIPHERS
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (C:\Program Files\Python311\Lib\site-packages\urllib3\util\ssl_.py)

However I found the problem, `DEFAULT_CIPHERS` is removed from `urllib3 2.0.0` while the program still imports it.
Thanks to [https://github.com/Yelp/elastalert/issues/2306](https://github.com/Yelp/elastalert/issues/2306)

**Comment by Jeffchen54** [comment]
Thanks for bringing up this issue and sorry for the late response. I will be returning to working on this project again soon and will include a script to fix this issue.
