### ISSUE TITLE
Not working properly, requesting help.

### ISSUE THREAD

**Issue by Kochisa** [Jeffchen54/KMPDownloader#17]
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\Moy\Desktop\KMP-Kemono-Downloader-0.6.1.3-pre\KMPDownloader.py
Traceback (most recent call last):
  File "C:\Users\Moy\Desktop\KMP-Kemono-Downloader-0.6.1.3-pre\KMPDownloader.py", line 12, in <module>
    import cfscrape
  File "C:\Users\Moy\AppData\Local\Programs\Python\Python311\Lib\site-packages\cfscrape\__init__.py", line 19, in <module>
    from urllib3.util.ssl_ import create_urllib3_context, DEFAULT_CIPHERS
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (C:\Users\Moy\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py)

**Comment by Jeffchen54** [comment]
Please view #16, I am working on a fix which will be available later this week but you can follow what is mentioned here for now.

**Comment by Jeffchen54** [comment]
Fixed in v0.6.1.4, you can reply to me here if you need any more help.

**Comment by Kochisa** [comment]
thx for your help :）
