### ISSUE TITLE
IMPORTANT!!! Kemono Implemented DDOS Protection

### ISSUE THREAD

**Issue by Jeffchen54** [Jeffchen54/KMPDownloader#31]
Kemono.party has recently implemented DDOS protection through the form of captcha puzzles. In order to use the downloader, you must visit Kemono.party first then complete the puzzle, afterwards you should be able to use the downloader to some extent. 

It is unknown to which extent the downloader is able to function to at this time. Although it is clear that Kemono is cracking down hard on downloaders at the moment and usage will be hindered for a while. I predict large downloads to be hit the hardest so --UPDATE and --REUPDATE switches may not function as advertised.

**Comment by TheThirdComputer** [comment]
Have they? I have not been asked to do any captcha yet...

Anyways, I will take advantage here and warn everyone else also doing mass scraping, to be ethical & responsible by always measuring your overall speed of download to avoid putting unnecessary pressure on the servers of a website, specially if the needs at hand are not urgent.

Being more specific, utilize the --wait switch and put 2 or 4 to the right to give the downloads some time to breath. After all, kemono is doing us a favor, and so should we return it too if we plan the website to stay afloat.

**Comment by Jeffchen54** [comment]
It does seem like they have reversed it but I had to solve a few puzzles when running it. I will add a bit more download restrictions to the program in the coming future, if this was a warning, we should listen to it.
