### ISSUE TITLE
Software stalling creating infinite folders.

### ISSUE THREAD

**Issue by TheThirdComputer** [Jeffchen54/KMPDownloader#33]
Problem: In the process of creating the containing folders, the software starts creating replicas of already finished folders up to around  of a 115 total for each original folder. 

I tried letting the software finish the creation of folders with the first link example, to check if the download of files was affected, but it reached up to 46000 folders, to what I decided it was too much and canceled it all.

example 1: https://kemono.party/patreon/user/140212
https://kemono.party/patreon/user/262481
https://kemono.party/patreon/user/12687536

It works normally when downloading the artists in chunks using ?o=50 at the end of each link.

Maybe an issue related to an update on Kemono?

EDIT: I used the last version, and this is the switch I used:
Python KMPDownloader.py --wait 2 -d I:\KMP-Kemono-Downloader-0.6.2.3v2-pre\logs

**Comment by Jeffchen54** [comment]
yeah it's due to a new kemono update, you can download #29 which should fix it. I'll pin this issue and try to get the next PR out as soon as I can which will still take a few days with testing that's needed. I'll pin this issue so everyone else can see what to do.

**Comment by TheThirdComputer** [comment]
Works wonderfully! Thank you very much!
