### ISSUE TITLE
Maybe a bug on 0.5.1

### ISSUE THREAD

**Issue by mario6714** [Jeffchen54/KMPDownloader#6]
Here the log from cmd:

C:\Users\m\Downloads\KMPDownloader-main>KMPDownloader.py -s -v -x "psd, clip" -d C:\Users\m\Downloads\KMPDownloader\
INFO:root:PARTIAL_UNPACK -> TRUE
INFO:root:UNZIP -> True
INFO:root:EXCLUDED -> ['psd', 'clip']
INFO:root:FOLDER -> C:\Users\m\Downloads\KMPDownloader\
Input a url, or type 'quit' to exit> https://kemono.party/patreon/user/38223307
(18)->0.png[████████████████████████████████████████████████████████████████████| 1.51M/1.51M [00:00<00:00, 9.22MiB/s]]CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/d2/67/d267f04d654affeab5aeb17fbf2e8fa798643007aac477a630b0f1d65aa01674.png?f=%E5%88%9D%E9%9F%B3%E3%83%9F%E3%82%AF114-2.png
                                                                                                                       CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/b3/e4/b3e42f934e38fa99b49ef5a2d2285d12fc468761dd99a22c646455501e88fb75.jpg?f=%E5%B3%B6%E9%A2%A86-1.jpg00:00, 6.91MiB/s]]
CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/b3/e4/b3e42f934e38fa99b49ef5a2d2285d12fc468761dd99a22c646455501e88fb75.jpg?f=%E5%B3%B6%E9%A2%A86-1.jpg
(260)->1.png[                                                                            | 0.00/1.77M [00:00<?, ?iB/s]]CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/ac/c3/acc3261328ecb226ccfb9b3b14d4e44ef0cf7cb64fa91e1c45b038afb0b3947b.png?f=%E9%8F%A1%E9%9F%B3%E3%83%AA%E3%83%B312-2.png
CRITICAL:root:File not downloaded correctly
CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/f5/31/f531efba26cafea5f89f8d5a85e5e855e7fb9de0f745626205ac864fcead458a.png?f=%E5%B7%9D%E5%86%857%E3%82%B5%E3%83%A0%E3%83%8D.png1.jpg[                                                                             | 0.00/141k [00:00<?, ?iB/s]]
CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/f5/31/f531efba26cafea5f89f8d5a85e5e855e7fb9de0f745626205ac864fcead458a.png?f=%E5%B7%9D%E5%86%857%E3%82%B5%E3%83%A0%E3%83%8D.png
CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/a1/9b/a19b4cbf989e2d5e7f7cb5fec1b1ef2446f6e6704746be45701b60e6a4443f65.png?f=%E5%B7%9D%E5%86%857.png

i hope this help, thanks

**Comment by mario6714** [comment]
C:\Users\m\Downloads\KMPDownloader-main>KMPDownloader.py -v -s -d C:\Users\m\Downloads\KMPDownloader\
INFO:root:UNZIP -> True
INFO:root:PARTIAL_UNPACK -> TRUE
INFO:root:FOLDER -> C:\Users\m\Downloads\KMPDownloader\
Input a url, or type 'quit' to exit> https://kemono.party/patreon/user/38223307
(0)->0.jpg[                                                                               | 0.00/164k [00:00<?, ?iB/s]]CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/b3/e4/b3e42f934e38fa99b49ef5a2d2285d12fc468761dd99a22c646455501e88fb75.jpg?f=%E5%B3%B6%E9%A2%A86-1.jpg
CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/b3/e4/b3e42f934e38fa99b49ef5a2d2285d12fc468761dd99a22c646455501e88fb75.jpg?f=%E5%B3%B6%E9%A2%A86-1.jpg
CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/d2/67/d267f04d654affeab5aeb17fbf2e8fa798643007aac477a630b0f1d65aa01674.png?f=%E5%88%9D%E9%9F%B3%E3%83%9F%E3%82%AF114-2.png
(61)->1.png[                                                                             | 0.00/1.77M [00:00<?, ?iB/s]]CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/ac/c3/acc3261328ecb226ccfb9b3b14d4e44ef0cf7cb64fa91e1c45b038afb0b3947b.png?f=%E9%8F%A1%E9%9F%B3%E3%83%AA%E3%83%B312-2.png
(178)->1.jpg[                                                                             | 0.00/141k [00:00<?, ?iB/s]]CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/f5/31/f531efba26cafea5f89f8d5a85e5e855e7fb9de0f745626205ac864fcead458a.png?f=%E5%B7%9D%E5%86%857%E3%82%B5%E3%83%A0%E3%83%8D.png>1.jpg[                                                                             | 0.00/171k [00:00<?, ?iB/s]]
CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/f5/31/f531efba26cafea5f89f8d5a85e5e855e7fb9de0f745626205ac864fcead458a.png?f=%E5%B7%9D%E5%86%857%E3%82%B5%E3%83%A0%E3%83%8D.png
(194)->0.jpg[                                                                             | 0.00/163k [00:00<?, ?iB/s]]CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/a1/9b/a19b4cbf989e2d5e7f7cb5fec1b1ef2446f6e6704746be45701b60e6a4443f65.png?f=%E5%B7%9D%E5%86%857.png9k [00:00<?, ?iB/s]]
(283)->0.png[                                                                            | 0.00/6.26M [00:00<?, ?iB/s]]CRITICAL:root:(502)Link provided cannot be downloaded from, possibly a dead third party link: https://kemono.party/data/10/a0/10a0aff4ff30fd981efff9e8c851d1e120cd3f7d983da30ab6ec91cd04f7e630.png?f=%E3%82%B5%E3%83%A0%E3%83%8D3-2.png

**Comment by Jeffchen54** [comment]
That isn't a bug with the code, Kemono party's server can't provide the data for some reason and is giving an HTTP 502 Bad gateway error. 

Let me demonstrate this:
https://kemono.party/patreon/user/38223307/post/51439228

This is one of the artist works from that artist you were trying to download from. If you click on the first image, it darkens but does not expand to the full resolution size. If you were to try and open it in another tab, you would get this window:
![image](https://user-images.githubusercontent.com/78765964/174676291-16c9598e-6d63-4bbc-aeb0-adad1d891ced.png)

The only thing you can do to mitigate this is to download the low res version manually or wait until Kemono has the links working again. There may be numerous reasons such as Kemono's server experiencing high traffic as a possible cause but I noticed several of the links above working again so you can try rerunning the program once in a while until all files are downloaded correctly.

This seems to be an issue with other artists at the moment as well, it might be better off to wait some time before trying again.

**Comment by mario6714** [comment]
No, is ok in that way, but for some reason after get multiple times the same error the program dont download more images anymore

**Comment by mario6714** [comment]
But let me keep testing and see what happen, thank, is really a cool program

**Comment by Jeffchen54** [comment]
The program is waiting for Kemono's HTTP response, its equal to accessing a webpage but waiting until the loading finishes.

The reason why you and I are having problems with Kemono is because one of their data caches are down:
https://status.kemono.party/
![image](https://user-images.githubusercontent.com/78765964/174677506-ab153c4a-8217-45b2-aeb9-0772d58f2482.png)

This matches up exactly with your Issue submission, unfortunately, you will continue to have issues until Kemono's servers are back up and running.

**Comment by mario6714** [comment]
Dont worry, thanks for the information, is great to heard the problem is in the site and not the program

**Comment by mario6714** [comment]
One question, any other site similar to Kemono?

**Comment by Jeffchen54** [comment]
I don't believe so, I haven't done much research on the topic so it might be better to consult other online forums than on here.
