### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'  

### ISSUE THREAD

**Issue by mx597014232** [Jeffchen54/KMPDownloader#9]
D:\code\kemono>python KMPDownloader.py -d D:/code/kemono/ -f D:/code/kemono/example.txt
Traceback (most recent call last):
  File "KMPDownloader.py", line 17, in <module>
    from DiscordtoJson import DiscordToJson
  File "D:\code\kemono\DiscordtoJson.py", line 20, in <module>
    class DiscordToJson():
  File "D:\code\kemono\DiscordtoJson.py", line 50, in DiscordToJson
    def discord_lookup_all(self, channelID:str|None, scraper:CloudflareScraper)->dict|list:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

hello, how to solve it?

**Comment by Jeffchen54** [comment]
Are you running Python 3.10? The "|" operand in return types was introduced in PEP 604 for python version 3.10.  Please double check your python version which you can do like as I did in the following screenshot:
<img width="241" alt="image" src="https://user-images.githubusercontent.com/78765964/185675656-53968fce-e066-4374-a9d9-c624df9923e8.png">

Pep 604: https://peps.python.org/pep-0604/

**Comment by Cathgao** [comment]
> Are you running Python 3.10? The "|" operand in return types was introduced in PEP 604 for python version 3.10. Please double check your python version which you can do like as I did in the following screenshot: <img alt="image" width="241" src="https://user-images.githubusercontent.com/78765964/185675656-53968fce-e066-4374-a9d9-c624df9923e8.png">
> 
> Pep 604: https://peps.python.org/pep-0604/

What should I do running on Python 3.9.13?
